name: AutoRun

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    #格林尼治时间22：11，东八区北京时间6：11
    - cron: 0 0 */1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run program
        run: |
          python3 dian.py
          
