name: AutoRun

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    #每2小时运行一次
    - cron: 0 */2 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run program
        run: |
          python3 dian.py
          
      - name: commit
        run: |
          git config --global user.email roywaller@126.com
          git config --global user.name roywaller
          git add .
          git commit -m "update" -a
		
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
